### ISSUE TITLE
Práctica Pokédex

### ISSUE THREAD

**Issue by ayrtoncg20** [ULL-ESIT-DSI-1920/dsi-p4-pokedex-ayrtoncg20#1]
@crguezl @ManzDev 

Ya he acabado esta práctica

**Comment by ManzDev** [comment]
Hola Ayrton,

Muy bien. Veo que controlas las asincronía con async/await, cosa que no es fácil con Parcel. Utilizas promesas para controlar las peticiones y realizando fetch para ellas.

Esta práctica muy bien, te pongo APTO.

Saludos,
